server:
  port: 8081

spring:
  application:
    name: weather-zuul-api

eureka:
  client:
    service-url:
      defaultZonet: http://localhost:8761/eureka/
zuul:
  routes:
    city:
      path: /city/**
      serviceId: weather-city
    data:
      path: /data/**
      serviceId: weather-data
