server:
  port: 8082

spring:
  redis:
    host: 94.191.34.212
    port: 6379
    erroKey: erroNum
    wsKey: wsKey
    erroChannel: erroChannel
  thymeleaf:
    cache: false
  application:
    name: weather-collection

eureka:
  client:
    service-url:
      defaultZonet: http://localhost:8761/eureka/