server:
  port: 8082

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    erroKey: erroNum
    wsKey: wsKey
    erroChannel: erroChannel
  thymeleaf:
    cache: false
  application:
    name: weather-collection

eureka:
  client:
    service-url:
      defaultZonet: http://localhost:8761/eureka/

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000