server:
  port: 8888

spring:
  application:
    name: weather-config

  cloud:
    config:
      server:
        git:
          uri:
          search-paths:
eureka:
  client:
    service-url:
      defaultZonet: http://localhost:8761/eureka/

