server:
  port: 8085

spring:
  application:
    name: weather-report

eureka:
  client:
    service-url:
      defaultZonet: http://localhost:8761/eureka/

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000