server:
  port: 8081

spring:
  application:
    name: weather-data
  redis:
    host: 94.191.34.212
    port: 6379
    erroKey: erroNum
    wsKey: wsKey
    erroChannel: erroChannel

eureka:
  client:
    service-url:
      defaultZonet: http://localhost:8761/eureka/